### ISSUE TITLE
Roadmap for v2.0.0

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#39]
I just wanted to bring this project "back to life" with some things I would love to see in upcoming version

Enhancements:
- [ ] Make a better readable `index.js` (#14)
- [ ] Integrate better testing (#29)

Features:
- [ ] Ability to include fonts into the project with less self-effort (#34)
- [ ] Using `gulp-inject` to include files into HTML
- [ ] Possibility to either use babel or `coffeeify` for CoffeeScript support
- [ ] Ability to use `gulp-postcss` instead of SCSS
- [ ] Updated default-page

Will continue editing, when I have some nice ideas.

What do you think?

**Comment by iDuuck** [comment]
@jhendley25

**Comment by jhendley25** [comment]
@iDuuck I agree. This project could use some life. I don't have time until next week (on vacation), but figuring out what a solid v2.0.0 looks like would be great. Thanks for putting this list together.

**Comment by iDuuck** [comment]
Added [run-sequence](https://github.com/OverZealous/run-sequence)

**Comment by iduuck** [comment]
Any news on this? @jhendley25

**Comment by jhendley25** [comment]
@iDuuck I definitely like the idea of adding gulp-postcss as an option, and adding wiredep and updating the default page. 

I don't know about adding coffeeify though... We kind of stepped away from Coffeescript in order to focus on es6 features, which is better in my opinion. Do you think adding Coffeescript support would be a valuable addition? 

How would you implement font integration? Extra options with default open source fonts (google, fontawesome, etc) that are automatically linked in the index/stylesheets?

I updated the list with a couple extra items. Let me know what you think.

**Comment by iduuck** [comment]
When it comes to font integration I think of a sub-generator, that is generating stylesheets with the right paths and desired font names.
